name: scoring

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  scoring:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Detect Chrome path
        run: echo "CHROME_PATH=$(which google-chrome)" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Run scoring
        run: bun --filter "@wsh-scoring-tool/scoring-runner" start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URI_BASE: ${{ vars.API_URI_BASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CHROME_PATH: ${{ env.CHROME_PATH }}
