# reference: CyberAgent (c) https://github.com/CyberAgentHack/web-speed-hackathon-2024-scoring-tool/blob/main/.github/workflows/request.yml

name: scoring

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  scoring:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    if: |
      contains(github.event.issue.labels.*.name, 'registration') && (
        (github.event_name == 'issues') || (
          github.event_name == 'issue_comment' &&
          !github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/retry') &&
          (github.actor == github.event.issue.user.login || github.actor == 'cp-20')
        )
      )
    steps:
      - if: github.event_name == 'issues'
        run: |
          gh api -X POST repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions \
            -f content=rocket
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'issue_comment'
        run: |
          gh api -X POST repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content=+1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Detect Chrome path
        run: echo "CHROME_PATH=$(which google-chrome)" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Run scoring
        run: bun --filter "@wsh-scoring-tool/scoring-runner" start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URI_BASE: ${{ vars.API_URI_BASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CHROME_PATH: ${{ env.CHROME_PATH }}
